- preswald/__init__.py
- preswald/components.py
- preswald/server.py
- preswald/templates/base.html
- requirements.txt
- setup.py
https://github.com/user-attachments/assets/a6db93b3-9776-4b67-a4f3-d6f8567630d1
> feat: Get the components to render from server.py

- frontend/src/components/Layout.jsx
- frontend/src/components/Sidebar.jsx
- frontend/src/components/TopBar.jsx
https://github.com/user-attachments/assets/c6eaaf5c-9b64-45c8-96d7-18a830d1119b
> feat: Make sidebar collapsible

- preswald/cli.py
Ran 
```
pip install -e ".[dev]" && python setup.py build_frontend && python -m build && pip install dist/preswald-0.1.26.tar.gz && preswald run examples/earthquakes/hello.py
```
and verified
> [DevX] On `preswald run` open the localhost link automatically

- frontend/src/components/pages/Connections.jsx
- preswald/data.py
- preswald/server.py
https://github.com/user-attachments/assets/56744028-e9a0-42ed-906d-31c2c35c45bb
> feat: Impl connections page to display config.toml

- examples/earthquakes/hello.py
- preswald/cli.py
Edited the deploy() function to be more user friendly and more descriptive- now tells users what script was deployed, the environment(locally, aws, gcp), and the port 
As well as a minor formating error in the earthquakes example with parenthesis
> Pretty Print

- frontend/src/App.jsx
- frontend/src/components/DynamicComponents.jsx
- frontend/src/components/pages/Dashboard.jsx
- frontend/src/utils/websocket.js
- preswald/__init__.py
- preswald/components.py
- preswald/core.py
https://github.com/user-attachments/assets/aeaa7162-7415-476d-9ba6-e3a249e5c6f2
> feat: Support grid layout by sizing components

- .gitignore
- frontend/src/lib/utils.js
- preswald/celery_app.py
- preswald/cli.py
- preswald/server.py
- preswald/utils.py
```
(preswald) jayanth.kumar@Jayanths-MacBook-Pro preswald % preswald run preswald_project/hello.py
Running 'preswald_project/hello.py' on http://localhost:8501 with log level INFO  🎉!
Starting Preswald server at http://localhost:8501
Will run script: /Users/jayanth.kumar/Downloads/work/structuredLabs/preswald/preswald_project/hello.py
Started background connections parsing task
INFO:     Started server process [64140]
INFO:     Waiting for application startup.
2025-01-17 00:47:51,805 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-17 00:47:51,817 - preswald.server - INFO - Looking for password with key: iris_psql {'data': {'iris_psql': {'password': 'MTg58h[KCvJx+&IY'}, 'mysql': {'password': ''}, 'json': {'api_key': ''}}, 'logging': …
```
> feat: Add conn parsing as bg task before server startup

- preswald/cli.py
`preswald --version` will now print the version and exit.
Example:
```
$ preswald --version
preswald, version 0.1.31
```
> Add `--version` flag to CLI

- preswald/cli.py
- preswald/deploy.py
> feat: Add prod variant deployment target

- preswald/cli.py
- preswald/deploy.py
> feat: Add user, api, app id for preswald proj depl

- frontend/src/components/widgets/SliderWidget.jsx
fix: ensures sliders step update functions properly
This PR addresses a small bug in which the slider step value (passed on creation of the slider widget) was not being reflected in the UI.
> Fixed bug in slider step update

- .github/pull_request_template.md
- .gitignore
- .pre-commit-config.yaml
- CONTRIBUTING.md
- README.md
- pyproject.toml
- setup.py
Add black, isort, and ruff for code formatting and linting. Additionally, added the pre-commit hook configuration to run these upon `git commit`
New feature (non-breaking change which adds functionality)
**Testing**
**Checklist**
> chore: add formatting and linting

- preswald/cli.py
- preswald/deploy.py
> feat: Add preswald deployments cli cmdn

- preswald/engine/runner.py
- preswald/engine/service.py
https://github.com/user-attachments/assets/5523c177-e53b-4552-b493-b7af16ccda4d
> fix: duplicate components on reload

- .pre-commit-config.yaml
- pyproject.toml
- setup.py
Replaced `black` with `ruff format`
**Testing**
> chore: Removed black in favor of ruff

- preswald/engine/managers/data.py
- preswald/engine/service.py
- preswald/interfaces/__init__.py
- preswald/interfaces/data.py
- preswald/templates/preswald.toml.template
- pyproject.toml
Added DuckDB based DataManager which allows for user-facing `connect` function. Users can use this to query/transform their data
**Testing**
Ran against a modified version of `hello.py` and `preswald.toml` in `examples/earthquakes`
**Checklist**
> Add connect() function which returns a DuckDBPyConnection object

- preswald/deploy.py
(preswald) jayanth.kumar@Jayanths-MacBook-Pro preswald % preswald deploy preswald_project/hello.py --target structured
2025-02-12 02:15:45,819 - preswald.utils - DEBUG - Logging configured with level DEBUG
Starting production deployment... 🚀
2025-02-12 02:15:45,870 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): corewald-ndjz2ws6la-ue.a.run.app:443
2025-02-12 02:15:49,331 - urllib3.connectionpool - DEBUG - https://corewald-ndjz2ws6la-ue.a.run.app:443 "POST /deploy HTTP/11" 200 None
i Starting deployment process
i Creating deployment files
i Packaging and uploading to Cloud Storage
i Triggering Cloud Build
i Building container image
i Deploying to Cloud Run
i Deployment completed successfully
i Your application is now live at: …
> feat: Add coreswald depl url

- preswald/deploy.py
> feat: Include git repo name in structured target req

- README.md
- examples/fires/hello.py
- examples/fires/preswald.toml
- preswald/templates/hello.py.template
- preswald/templates/preswald.toml.template
- preswald/tutorial/hello.py
- preswald/tutorial/preswald.toml
Updated the `README.md`, the `tutorial` directory, the default `templates`, and some examples around reading data sources correctly.
**Testing**
Re-ran `preswald run` in the `tutorial` dir, in each of the examples, and in a new project created via `preswald init`
**Checklist**
> Fix README and examples for connect function

- preswald/cli.py
- preswald/deploy.py
- preswald/engine/telemetry.py
- preswald/tutorial/preswald.toml
2025-02-22 00:51:54,534 - preswald.engine.telemetry - INFO - Sending telemetry data: {'preswald_version': '0.1.38', 'preswald_slug': 'preswald-tutorial', 'project_name': 'Preswald Tutorial', 'data_sources': ['csv'], 'event_type': 'command_execution', 'command': 'deploy', 'command_args': {'script': 'hello.py', 'target': 'local', 'port': 8501, 'log_level': 'INFO', 'has_github': False, 'has_api_key': False}}
> feat: telemetry

- examples/travel/README.md
- examples/travel/data/travel_details_data.csv
- examples/travel/hello.py
- examples/travel/preswald.toml
Name: Adding an example dataset
About: Adding a travel dataset example using preswald
labels: example
Added a new example demonstrating preswald's usage with a travel dataset.
**Testing**
Tested it out locally. 
[Screen Recording 2025-02-27 at 18.21.01.mov](https://github.com/user-attachments/assets/a6e04d63-a350-497f-af65-a15c79786f07)
**Checklist**
> Add travel example

- README.md
The instructions for writing your first app were outdated. These updates now include the latest hello template code, and the run command has been revised to reflect the addition of an entrypoint in preswald.toml.
**Testing**
Manually tested:
**Checklist**
~~- [ ] My code follows the style guidelines of this project~~
~~- [ ] I have performed a self-review of my own code~~
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
> chore: Update README instructions for writing first app

- preswald/tutorial/README.md
> Reduce package size from 11MB to 2MB by deleting gif

- autotest/deployments/structured/test.sh
- examples/real_estate/pyproject.toml
- examples/travel/pyproject.toml
```
(preswald) jayanth.kumar@Jayanths-MacBook-Pro preswald % ./autotest/deployments/structured/test.sh
Processing directory: examples/earthquakes/
Running deployment...
Deployment successful!
Access your app at: https://preswald-earthquakes-jwc7gft8-2jj4zpd3za-ue.a.run.app
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<link rel="icon" type="image/x-icon" href="/assets/favicon.ico?timestamp=$1741273067.7718945" />
<link rel="shortcut icon" type="image/x-icon" href="/assets/favicon.ico?timestamp=$1741273067.7718945?timestamp=1741273067.7745552" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Preswald Project</title>
<script type="module" crossorigin src="/assets/index-D4DgCJ84.js"></script>
<link rel="stylesheet" crossorigin …
```
> feat: Add autotest for structured depls

- CONTRIBUTING.md
- examples/earthquakes/README.md
- examples/finance/README.md
- examples/fires/README.md
- examples/music/README.md
- examples/netflix/README.md
- examples/network/README.md
- examples/real_estate/README.md
- examples/travel/README.md
- examples/voice/README.md
---
name: Edit readme's
title: ''
labels: ''
assignees: '@ucheochuba'
---
Fixes #(issue)
A clear and concise description of the changes made in this pull request.
**Testing**
> update command in contributing readme

- autotest/deployments/structured/test.sh
- preswald/cli.py
https://github.com/StructuredLabs/corewald/pull/18#issuecomment-2711502961
> feat: update depl stop to be script name independent

- preswald/deploy.py
Fixes StructuredLabs/preswald#45
> Add formatting to get_container_name

- examples/social-media-trends/.gitignore
- examples/social-media-trends/README.md
- examples/social-media-trends/data/social-media-trends.csv
- examples/social-media-trends/hello.py
- examples/social-media-trends/preswald.toml
- examples/social-media-trends/pyproject.toml
Added Social Media Trends Example Document
This PR adds a Social Media Trends Example Document to the main repository. The example demonstrates how the app dynamically filters the real dataset using custom SQL queries to retrieve relevant filtered data.  
The app provides custom data visualizations, enabling users to gain insights through:  
- Shares-Based Analysis (User Control) 
- Engagement-Based Analysis  
- Region-Based Analysis  
These visualizations leverage Preswald for quick deployment, allowing users to rapidly build and deploy custom dashboards on their data in just minutes.
> add social-media-trends example

- docs/addnewcomponent.mdx
- docs/docs.json
https://github.com/user-attachments/assets/df806040-9ea6-4846-a333-7f36a216aa62
> Add New Component docs

- autotest/deployments/structured/test.sh
```
(preswald) jayanth.kumar@Jayanths-MacBook-Pro preswald % ./autotest/deployments/structured/test.sh
=========================================
Processing directory: examples/SP500/
=========================================
[ OK ] Copied .env file [Time: 00:00:00]
Running initial deployment...
[ OK ] Deployment successful! [Time: 00:01:01]
Cloud Run URL: https://sp500-879549-7qcm63gf-2jj4zpd3za-ue.a.run.app
Preswald App URL: https://sp500-879549-7qcm63gf.preswald.app
[ OK ] Verified Cloud Run URL accessibility [Time: 00:00:00]
Response preview:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<link rel="icon" type="image/x-icon" href="/assets/favicon.ico?timestamp=$1741878077.9557457" />
[ OK ] Verified Preswald App URL accessibility [Time: 00:00:01]
Response preview: …
```
> feat: Update structured target depl autotest

- examples/titanic/README.md
- examples/titanic/data/sample.csv
- examples/titanic/hello.py
---
title: ''
labels: ''
assignees: ''
---
Fixes #(issue)
A clear and concise description of the changes made in this pull request.
**Testing**
**Checklist**
> Added titanic example

- .gitignore
- autotest/deployments/gcp/test.sh
- autotest/deployments/local/test.sh
- preswald/cli.py
- preswald/deploy.py
```(preswald) jayanth.kumar@Jayanths-MacBook-Pro preswald % ./autotest/deployments/gcp/test.sh
Starting GCP deployment tests sequentially for all example projects
=================================================================
=================================================================
Testing project: fires
=================================================================
[INFO] Starting GCP deployment test for fires
[INFO] Deploying to GCP...
Running: preswald deploy --target gcp
DEBUG: Full deployment output:
[SUCCESS] Deployment successful! [Time: 00:00:48]
[INFO] Cloud Run URL: https://preswald-app-fires-ndjz2ws6la-uw.a.run.app
[INFO] Testing deployed application...
[SUCCESS] Application is accessible [Time: 00:00:01]
DEBUG: Response preview:
[INFO] Stopping GCP deployment... …
```
> feat: gcp depl target autotest

- docs/addnewcomponent.mdx
---
name: Updated addnewcomponent docs
about: Updated docs to fix issue #194 
title: ''
labels: ''
assignees: ''
---
Fixes #194 
Updated docs to include frontend rebuild step when creating new component.
Below is an image showing the new step in the docs:
**Testing**
Tested steps with the new instructions and things appear to be working.
**Checklist**
> Updated addnewcomponent docs

- preswald/engine/managers/data.py
Original PR #154 by @varnitsingh
Additional fix:
- Add region param to config for current duckdb version
> Rebasing (and fixing) PR #154 (https://github.com/StructuredLabs/preswald/pull/154)

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/DynamicComponents.jsx
- frontend/src/components/widgets/TableViewerWidget.jsx
- package-lock.json
- package.json
- preswald/interfaces/components.py
This PR replaces the traditional HTML table in TableViewerWidget.jsx with AG Grid, significantly enhancing performance, usability, and flexibility.
-- Added Features:
1. Sorting & Filtering – Easily organize and search data within the table.
2. Column Resizing & Reordering – Users can adjust column widths and move them as needed.
3. Row Selection – Supports multi-select for better interactivity.
4. Basic CSV Export – Allows exporting data in CSV format.
5. Custom Cell Renderers – Enables flexible formatting and data representation.
-- Performance Optimizations:
1. Implemented virtual scrolling for handling large datasets efficiently.
2. Optimized column rendering for better responsiveness.
-- UI & Usability Improvements:
1. Enhanced styling to align with the application's overall design. …
> AG-grid integration 

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.jsx
- frontend/src/components.css
- frontend/src/components/DynamicComponents.jsx
- frontend/src/components/Layout.jsx
- frontend/src/components/LoadingState.jsx
- frontend/src/components/PreswaldBadge.jsx
- frontend/src/components/pages/Dashboard.jsx
- frontend/src/components/ui/aspect-ratio.tsx
- frontend/src/components/ui/sidebar.tsx
- frontend/src/components/widgets/ImageWidget.jsx
- frontend/src/components/widgets/MarkdownRendererWidget.jsx
- frontend/src/components/widgets/TopbarWidget.jsx
- frontend/src/styles.css
- frontend/tailwind.config.js
- preswald/tutorial/hello.py
- preswald/tutorial/preswald.toml
- cleaned up markdown code highlighting (removed Prism, simplified `MarkdownRendererWidget`)
- fixed topbar layout/styling (new minimal `TopbarWidget`, adjusted padding/margins)
- added topbar Preswald badge link (`PreswaldBadge` component with fixed top-right link)
- revamped sidebar:
- updated styles + hover interactions
- added image/logo widget
- simplified image widget component (no more aspect ratio handling)
- tetris-style animated loading state (`LoadingState.jsx`)
- updated dashboard + app layout to use new loading and badge components
- deleted unused aspect-ratio UI component
- added new sidebar theme vars to `styles.css` and `tailwind.config.js`
- updated tutorial ordering in `hello.py` and added image demo step
https://github.com/user-attachments/assets/cbccbe61-de6a-4ceb-a77d …
> Preswald App Redesign

- docs/sdk/get_df.mdx
- docs/sdk/playground.mdx
- docs/sdk/query.mdx
- docs/usage/examples.mdx
Consolidated table component in place of view and updated the documentation.
> Updated docs with removed view component

- frontend/src/components/TableOfContents.jsx
- frontend/src/components/ui/sidebar.tsx
---
name: Table of Contents added to Sidebar
title: 'Table of Contents Navigation Component'
labels: ''
assignees: ''
---
In this pull request, I've added a dynamic Table of Contents component to the sidebar navigation. It scans for header elements (h1, h2, h3) within the `dashboard-container` and map these clickable navigation headers to the sidebar that scroll smoothly to their respective sections of the data analysis document. These changes will improve user navigation experience for long documentation or data analysis pages.
**Testing**
I ran the testing on the given examples locally, such as Iris and Earthquakes using the sidebar() component in their respective `hello.py` code. …
> Feature - Added Table of Contents to Sidebar

- docs/coreconcepts.mdx
- docs/sdk/workflow.mdx
---
title: "docs: add reactive runtime and DAG execution docs"
labels: documentation
assignees: ''
---
Fixes # (N/A – no issue filed)
This PR improves the documentation around Preswald’s reactive runtime and DAG-based workflow execution. Specifically:
- Added a new section to `coreconcepts.mdx` detailing how the reactive runtime works, including how dependencies are tracked and how recomputation is minimized.
- Added a new section to `workflow.mdx` explaining two ways to define workflow dependencies: manual and automatic (inferred from function arguments).
- Included examples for both manual and inferred dependency declarations.
- Linked to the workflow guide from core …
> docs: document reactive runtime and manual vs inferred dependencies

- CONTRIBUTING.md
---
title: 'docs: add Git rebase + fork sync guidance to CONTRIBUTING.md'
labels: documentation
assignees: ''
---
Fixes # (none)
This PR updates `CONTRIBUTING.md` with a new section on working with forks and keeping branches in sync. It explains why rebasing is preferred over merging when maintaining feature branches and includes links to trusted external guides from GitHub and Atlassian. This should help contributors avoid messy histories and coordinate more effectively across forks.
**Testing**
- Manually verified that the section renders correctly in markdown.
- Clicked all external links to confirm they are accurate and up-to-date.
- Confirmed …
> docs(contributing): add section on working with forks & rebasing

- preswald/utils.py
Callsite detection breaks in pyodide because `sys.base_prefix` (which is used to detect if python std lib is being used). Callsite detection itself is used when assigning unique ids to components (via the `with_render_tracking` decorator)
**Testing**
Tested in both pyodide and non-pyodide (regular `preswald run`) environments.
**Checklist**
> Fixed callsite detection to work inside pyodide

- frontend/src/components/Layout.jsx
Remove 'Built by Preswald' branding if rendered in pyodide
**Testing**
Checked examples in pyodide and non-pyodide
**Checklist**
> Remove 'Built by Preswald' branding if rendered in pyodide

- frontend/src/components/DynamicComponents.jsx
- frontend/src/components/ui/sidebar.tsx
- frontend/src/components/widgets/AlertWidget.jsx
- frontend/src/components/widgets/BigNumberWidget.jsx
- frontend/src/components/widgets/ButtonWidget.jsx
- frontend/src/components/widgets/ChatWidget.jsx
- frontend/src/components/widgets/CheckboxWidget.jsx
- frontend/src/components/widgets/DAGVisualizationWidget.jsx
- frontend/src/components/widgets/DataVisualizationWidget.jsx
- frontend/src/components/widgets/FastplotlibWidget.jsx
- frontend/src/components/widgets/ImageWidget.jsx
- frontend/src/components/widgets/JSONViewerWidget.jsx
- frontend/src/components/widgets/MarkdownRendererWidget.jsx
- frontend/src/components/widgets/MatplotlibWidget.jsx
- frontend/src/components/widgets/PlaygroundWidget.jsx
- frontend/src/components/widgets/ProgressWidget.jsx
- frontend/src/components/widgets/SelectboxWidget.jsx
- frontend/src/components/widgets/SeparatorWidget.jsx
- frontend/src/components/widgets/SidebarWidget.jsx
- frontend/src/components/widgets/SliderWidget.jsx
- frontend/src/components/widgets/SpinnerWidget.jsx
- frontend/src/components/widgets/TableViewerWidget.jsx
- frontend/src/components/widgets/TextInputWidget.jsx
- frontend/src/components/widgets/TopbarWidget.jsx
- frontend/src/components/widgets/UnknownWidget.jsx
- preswald/cli.py
- preswald/engine/runner.py
- preswald/main.py
- preswald/utils.py
This PR introduces a robust and automated PDF export feature in Preswald that ensures all components are fully rendered before capturing the document, preventing partially rendered charts or empty placeholders in the final report.
Key Features:
1. Full component visibility check before PDF export : Uses getElementById() + visibility checks to ensure each layout element is rendered and visible in the DOM.
2. Supports all component types: Works with any registered widget: plotly, table, text, chat, sidebar, image, json_viewer, etc.
3. Abort with warnings if components are missing:  Provides detailed console output listing any missing elements before failing gracefully.
4. Custom layout-safe PDF generation with CSS : Ensures plotly charts and large components are not split across pages using …
> Feature: Export pdf with component rendering check

- .github/workflows/release.yml
---
title: ''
labels: ''
assignees: ''
---
Fixes #(issue)
A clear and concise description of the changes made in this pull request.
**Testing**
**Checklist**
> fix: update pypi env var

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.jsx
- frontend/src/backend/service.js
- frontend/src/backend/worker.js
- frontend/src/components/DynamicComponents.jsx
- frontend/src/utils/websocket.js
- frontend/vite.config.js
- preswald/browser/boot.js
- preswald/browser/entrypoint.py
- preswald/browser/virtual_service.py
- preswald/cli.py
- preswald/utils.py
This PR introduces a Web Worker implementation using Comlink to handle Pyodide initialization and execution in a separate thread, improving the main thread's performance and responsiveness.
- Added `comlink` v4.4.2 for streamlined Web Worker communication
- Created new worker-related files:
- `frontend/src/backend/service.js`: Worker factory service
- `frontend/src/backend/worker.js`: Main worker implementation with Pyodide integration
The new `PreswaldWorker` class provides:
- Pyodide initialization and package management
- Script execution handling
- Component state management
- Filesystem operations
- Branding information retrieval
- Enhanced logging in `App.jsx` for better connection tracking
- Removed redundant console logs
- Code cleanup in `DynamicComponents.jsx`
```javascript
// …
```
> feat: Add HTML Export via WebWorker + Comlink

- frontend/src/backend/worker.js
- preswald/browser/entrypoint.py
- preswald/cli.py
- preswald/utils.py
Quick addition to make preswald HTML Export available as a function within the worker. Existing behavior works as is.
> feat: Create preswaldHTMLExport entrypoint for use in worker

- frontend/src/App.jsx
- frontend/src/components.css
- frontend/src/components/ErrorsReport.jsx
- frontend/src/components/pages/Dashboard.jsx
- preswald/engine/base_service.py
- preswald/engine/runner.py
- preswald/engine/transformers/reactive_runtime.py
- preswald/interfaces/render/error_registry.py
- preswald/interfaces/render/registry.py
---
title: 'feat(errors): implement error handling and reporting for AutoAtomTransformer'
labels: 'enhancement'
assignees: ''
---
tracked by: https://trello.com/c/xELESg6q/2719-implement-error-handling-and-reporting-for-autoatomtransformer
This PR implements structured error handling and reporting for the `AutoAtomTransformer` class. Major changes include:
- Introduced `_safe_register_error` for consistent error reporting with AST context
- Registered transformation errors for failure points during lifting, dependency analysis, and unparsing
- Added `AstHaltError` to cleanly abort transformation without crashing
- Exposed `has_errors()` from `BasePreswaldService` …
> feat(errors): implement error handling and reporting for AutoAtomTransformer
