StructuredLabs/preswald

preswald/server.py
Create a fallback for local `preswald` CLI installs when pkg_resources fails.
=> Fix `BASE_DIR` for local preswald installs

.pre-commit-config.yaml, pyproject.toml, setup.py
Remove use of `isort` for import sorting, and instead just using `ruff` with additional config.
**Why:**
`isort was conflicting with `ruff`
**Testing**
Ran pre-commit hooks and verified that everything was working without `isort`
=> [Cleanup] Reemove isort and use only ruff

.pre-commit-config.yaml, preswald/cli.py, preswald/templates/hello.py.template, preswald/templates/preswald.toml.template
- Running `preswald_init` now gives users a ready-to-go example with data and visuals, no extra setup needed.
- 
**What Changed:**  
- When you run `preswald_init`, it now:
- Creates a `data/` directory.
- Drops in a `sample.csv` file.
- Auto-generates a basic Plotly scatter plot using that CSV.
**Details:**
1. **Directory & File Additions:**
- `data/` dir gets created alongside `images/`.
- `sample.csv` gets copied into `data/` on init.
2. **Plot Setup:**
- Updated `hello.py.template` to load `sample.csv` and plot `Quantity vs. Value` using Plotly Express.
- The plot has labeled points, light blue markers, and a clean white background.
- Also displays the DataFrame below the plot using `view(df)`.
3. **Config Tweaks:**
- Removed PostgreSQL config from `preswald.toml.template`.
- Added …
=> Add `data/` dir, `sample.csv`, and default Plotly chart to `preswald_init`

preswald/cli.py, preswald/main.py, preswald/utils.py
preswald.toml port config takes precedence over cli argument. but, cli was still printing the cli argument for port (using the preswald.toml behind the scenes)
this fixes the printing mismatch.
=> Fix port printing issue

docker/preswald_app.Dockerfile, docker/test/voice_app.Dockerfile, preswald/deploy.py
```
(preswald) jayanth.kumar@Jayanths-MacBook-Pro voice % preswald deploy --target gcp                                  
Using Google Cloud project: structured-app-prod
Building Docker image preswald-app-voice-log-debugger for GCP deployment...
Running build command in /Users/jayanth.kumar/Downloads/work/structuredLabs/preswald/examples/voice/.preswald_deploy: docker buildx build --platform linux/amd64 -t preswald-app-voice-log-debugger --load .
[+] Building 7.3s (9/9) FINISHED                                                           docker-container:happy_jang
=> [internal] load build definition from Dockerfile                                                              0.0s
=> => transferring dockerfile: 135B …
```
=> fix: resolve gcp depl

preswald/browser/entrypoint.py
- Exposing a dummy deploy function. 
Tested it with:
Note: If you've made changes to preswald locally. Build the frontend (js static assets), and build the python package. Expose it via an http-server locally. 
```
git pull 
python setup.py build_frontend
python -m build
npm install -g http-server
cd dist && http-server -p 8000 --cors
```
By default, runewald will download and use the most up-to-date version of preswald from PyPI. Otherwise, expose preswald via local http-server. 
Note: static assets have been added to runewald
```
bash ./scripts/sync-preswald.sh 
```
Copies from preswald directory to runwald directory (output of build_frontend function) 
```
cd public/
cd preswald-assets/
npm run dev
```
=> Expose dummy deploy function

.gitignore, frontend/src/App.jsx, frontend/src/components.css, frontend/src/components/DynamicComponents.jsx, frontend/src/components/Sidebar.jsx, frontend/src/components/TopBar.jsx, frontend/src/components/pages/Dashboard.jsx, frontend/src/components/widgets/AlertWidget.jsx, frontend/src/components/widgets/ButtonWidget.jsx, frontend/src/components/widgets/CheckboxWidget.jsx, frontend/src/components/widgets/ConnectionInterfaceWidget.jsx, frontend/src/components/widgets/DAGVisualizationWidget.jsx, frontend/src/components/widgets/DataVisualizationWidget.jsx, frontend/src/components/widgets/ImageWidget.jsx, frontend/src/components/widgets/MarkdownRendererWidget.jsx, frontend/src/components/widgets/ProgressWidget.jsx, frontend/src/components/widgets/SelectboxWidget.jsx, frontend/src/components/widgets/SliderWidget.jsx, frontend/src/components/widgets/SpinnerWidget.jsx, frontend/src/components/widgets/TableViewerWidget.jsx, frontend/src/components/widgets/TextInputWidget.jsx, frontend/src/components/widgets/UnknownWidget.jsx, frontend/src/index.css, frontend/src/main.jsx, package-lock.json, package.json
This PR moves all hard-coded Tailwind styling strings into `components.css` and uses `@apply` in Tailwind for styling. This is the first step to separate styles from component definitions. A future pass will be needed to group similar styles for better consistency.  
1. Built the frontend with:  
```bash
python setup.py build_frontend
```
2. Verified components work by running:  
```bash
cd preswald/tutorial
preswald run
```
3. Confirmed everything functions correctly at `localhost:8501`.
=>  Move Tailwind Styles to `components.css`

preswald/cli.py, setup.py
Fixes #438 
This PR ensures that GitHub usernames provided via the `--github` argument in the `deploy` command are case-insensitive. The change converts the username to lowercase before passing it to the deployment function.  
- **Lowercased GitHub username** before sending it to the deployment API.
- **Handled None values** safely to avoid `AttributeError` on `.lower()`.
- **Prevents 400 Bad Request errors** caused by mismatched GitHub username casing.
- **Local Testing**:
- Deployed with a mixed-case GitHub username (e.g., `TestUser`).
- Confirmed that it **lowercases correctly** and does not cause a `400 Bad Request`.
- Verified that deployment works as expected.
```bash
(.venv) dustfinger@primus:~/dev/preswald/community_gallery/stack_overflow_developer_trends$ preswald deploy --target …
```
=> fix: ensure GitHub usernames are case insensitive in deployment

examples/iris/hello.py, frontend/src/components/DynamicComponents.jsx, frontend/src/components/widgets/MatplotlibWidget.jsx, preswald/interfaces/__init__.py, preswald/interfaces/components.py
This PR adds support for visualizing data using Matplotlib. Key changes include:
- Backend integration to generate Matplotlib plots and serve them as images.
- New MatplotlibWidget.jsx to display plots in the frontend.
- Added a sample sine wave plot for testing.
=> Added matplotlib component

setup.py
This PR adds two missing dependencies to `setup.py`:
- `fastplotlib[imgui]~=0.3.0`
- `imageio~=2.37.0`
These are required to support examples like `hello.py` that use the `fastplotlib` component. Without them, users will encounter import errors when trying to run those examples out of the box.
Running `preswald run` on the `hello.py` example currently fails unless these dependencies are manually installed. Adding them to `CORE_DEPENDENCIES` ensures a smoother setup experience for users and contributors.
Let me know if you'd like me to add tests or docs alongside this!
=> fix(setup): add missing fastplotlib and imageio dependencies

frontend/src/components.css, frontend/src/components/ui/select.tsx
Fixes #387 
fixing the styling of select box so that it doesn't overflow when there are a lot of select items.
before:
after:
**Checklist**
=> fix: selectbox overflow styling

frontend/src/App.jsx
-
Small fix to improve the initial loading state of the app.
Previously it used to show text `No components to display` during first load after websocket connection is successful but components aren't loaded yet. Added a new state to check if components are loaded and keep showing loading indicator until then which prevents showing `No components to display` text during first load.
**Testing**
Before:
https://github.com/user-attachments/assets/10b02668-6f89-4d94-83eb-9643aac85099
After:
https://github.com/user-attachments/assets/3f3437d4-d9b6-4bd5-964a-34ae89ea8e4f
**Checklist**
=> fix: improve initial loading state

preswald/deploy.py
Fixes [#589](https://github.com/StructuredLabs/preswald/issues/589)
This pull request modifies the deployment code under `deploy.py` to pass the configured port from `preswald.toml` into `deploy_to_local`, and ensures that Docker maps the configured port to the corresponding in the container, instead of always searching ports from 8501.
- Bug fix (non-breaking change which fixes an issue)
**Testing**
1. Modify the project port in an example project, i.e. `examples/iris` to another port such as 8000
2. Run `preswald deploy` in the example project folder
3. `curl` or visit `http://localhost:8000` in the browser to verify the server is accessible on the configured port
**Checklist**
=> Fix: Use configured port for local deployments

preswald/deploy.py
---
title: 'Fix TypeError in deploy.py for Python 3.7+ compatibility'
labels: 'bug'
assignees: ''
---
Fixes #218   
This PR replaces the `|` (union operator) in `deploy.py` with `Union` from the `typing` module.  
- **Reason**: The `|` operator is only supported in Python 3.10+, while Preswald supports Python 3.7+.  
- **Fix**: Updated function return type to use `Union[...]`.  
I verified the fix by running:  
✅ `preswald init project` in a Python 3.9 environment (no TypeError).  
✅ Linted the code to ensure style consistency.  
---
=> Fix TypeError by replacing | with Union for Python 3.7+ support

examples/iris/hello.py, frontend/src/App.css, frontend/src/components.css, frontend/src/components/DynamicComponents.jsx, frontend/src/components/Layout.jsx, frontend/src/components/ui/sidebar.tsx, frontend/src/components/widgets/ChatWidget.jsx, frontend/src/components/widgets/MarkdownRendererWidget.jsx, frontend/src/components/widgets/SidebarWidget.jsx, frontend/src/components/widgets/TableViewerWidget.jsx, frontend/src/index.css, preswald/__init__.py, preswald/interfaces/components.py, setup.py
- cleans up layout styles in `App.css`, removes extra padding/margins, centers content
- redesigns the sidebar (mobile + desktop): collapsible behavior, new layout, styling tweaks, removes old portal logic
- rewrites `ChatWidget`: adds settings toggle for API key input, improves empty/error states, better loading indicators
- simplifies `TableViewerWidget`: cleaner structure, removes title/export logic, responsive layout with better default sizing
- updates `MarkdownRendererWidget`: strips out legacy markdown classes, uses cleaner tailwind prose styling
- removes redundant markdown styles from `components.css`
- adjusts layout structure in `Layout.jsx`: removes sidebar portal logic, simplifies flex structure
- bumps version to `0.1.50`
cleaner UI across the board + smaller bundle from …
=> Preswald Frontend Redesign

frontend/src/components/DynamicComponents.jsx, frontend/src/components/widgets/PlaygroundWidget.jsx, package-lock.json, package.json, preswald/interfaces/components.py
- refactors `PlaygroundWidget` UI to use `Card`, `Editor`, and paginated `Table`
- adds support for showing query results with column headers and rows
- adds pagination logic (10 rows per page)
- runs query on button click and resets page to 1
- displays query errors using `Alert` component
- adds `@monaco-editor/react` for SQL editing UI
- backend now serializes DataFrame to `columnDefs` + `rowData` format
- handles NaNs, None, and NumPy types during serialization
https://github.com/user-attachments/assets/e6c5e15b-f1c3-493f-849e-51d298c0a3ef
=> Fix query playground

frontend/package-lock.json, preswald/browser/virtual_service.py, tests/pyodide_test.html
Fixes #511 (Fastplotlib WebSocket streaming) — this change builds on that by improving the `virtual_service` behavior
---
- Updates `handle_message_from_js` to reliably convert incoming messages from the browser into Python dicts using a JSON workaround, due to limitations in the available Pyodide build (0.27.2, but missing `to_py`)
- Ensures compatibility with legacy JS message shapes while allowing expanded message structure
- Adds rerun skip logic to `VirtualPreswaldService`: if component state is unchanged, the rerun is skipped and not broadcast to other clients
- Logs a debug message when reruns are skipped due to no actual state change
- Adds `eslint-config-prettier` to `package-lock.json` (already in `devDependencies`) — likely missed …
=> feat: skip reruns in virtual service if no state changes detected

frontend/package-lock.json, frontend/package.json, frontend/src/components/widgets/MarkdownRendererWidget.jsx
- Adds anchor links to markdown headings in `MarkdownRendererWidget`
- Adds hoverable link icon next to each heading using `Link2Icon`
- Uses `remark-slug` and `remark-autolink-headings` in `remarkPlugins`
- Scrolls to heading when URL hash is present (on initial load)
- Applies highlight style to target heading
- Sets `scrollPaddingTop` globally for better alignment
- Cleans up syntax highlighting logic for code blocks
- Updates `package.json` with new markdown plugins
https://github.com/user-attachments/assets/da9ba765-3212-4f56-9563-5525823dba45
=> Add anchor link support for markdown headings

examples/earthquakes/hello.py, examples/fires/hello.py, examples/iris/hello.py, examples/user_event/hello.py, preswald/browser/virtual_service.py, preswald/engine/base_service.py, preswald/engine/managers/data.py, preswald/engine/runner.py, preswald/engine/server_service.py, preswald/templates/hello.py.template, preswald/tutorial/hello.py
Fixes duplication happening when `connect()` is called multiple times (as it is due to script re-renders)
Ensure `connect` is idempotent by creating a cache of source configs in `preswald/engine/managers/data.py`
Call `connect()` in `runner.py` in `run_script` so user doesn't have to include it in their script.
**Testing**
Ran local and auto-test on the examples.
**Checklist**
=> Remove need to call connect explicitly

preswald/engine/utils.py
(fix #692)
name: Fix Selectbox Crash
about: Resolves the NameError in selectbox when HASH_PATTERN is undefined (#692)
title: "fix: qualify HASH_PATTERN reference in RenderBuffer._ensure_hash (fixes #692)"
labels: "bug, good first issue"
assignees: "apoorv-narayanam"
---
Fixes #692 --> HASHPATTERN NOT FOUND
This PR fixes a NameError when the selectbox value is hashed. 
- Qualify HASH_PATTERN as self.HASH_PATTERN in RenderBuffer._ensure_hash. in /preswald/engine/utils.py
**Testing**
Earlier:
for the code
the result
however after the fix.
the results for changing to state to B and C one after the other
**Checklist**
=> fix: [BUG] Selectbox selection results in crash #692

preswald/engine/runner.py
---
title: 'fix(runtime): fallback to full rerun when DAG dependencies are missing'
labels: 'bug'
assignees: 'trevor-wilson'
---
Fixes #698
This PR adds a fallback in `ScriptRunner.rerun()` to re-execute the entire script if no reactive dependencies are detected via DAG analysis. This covers top-level Preswald scripts that do not use `@workflow.atom` decorators and ensures interactivity is preserved even when DAG-based tracking is absent.
**Testing**  
Tested manually using two scripts:
- One without any `@workflow.atom` decorators (`slider` + `text` at top level)
- One with workflow-based atoms (slider input used to render dynamic text)
Both …
=> fix(runtime): fallback to full rerun when DAG dependencies are missing

preswald/engine/managers/data.py
---
title: 'fix(csv): disable normalize_names to preserve original column names'
labels: ''
assignees: ''
---
Fixes #N/A (no GitHub issue created)
This PR updates the DuckDB `read_csv_auto` invocation in `CSVSource` to explicitly set `normalize_names=false`.  
This prevents DuckDB from automatically converting column names like `"sepal.length"` into `"sepallength"`, which was causing example scripts (e.g., `hello.py`) to fail due to mismatched column names.
**Testing**  
Manually tested by running the unmodified `examples/iris/hello.py` script and confirming that all Plotly charts render correctly using the original column names from `iris.csv`. …
=> fix(data): preserve original column names in CSV sources

frontend/src/components.css, frontend/src/components/ui/sidebar.tsx
This PR fixes the alignment of the sidebar logo when in collapsed mode. Along with that, rounded edges have been added for the logo for smoother appearance.
Fixes #41 
For aligning it correctly, left margin has been added to sidebar-logo class. For rounded edges, border-radius is also added.
**Testing**
Before
After
**Checklist**
=> Fix sidebar logo alignment

docs/sdk/get_df.mdx, docs/sdk/query.mdx, preswald/engine/managers/data.py
Users can avoid the `preswald.toml` flow for files, and instead use file paths (relative to where the preswald server is run) in `query` and `get_df`. `connect` works as before.
**Testing**
Ran existing uses of `get_df` and `query` in examples to confirm that behavior was identical (wether dfs were fetched from files directly or via `preswald.toml`)
**Checklist**
=> [FEATURE] Add ability to connect via source path

preswald/main.py
Fixes #651 
Replaces `makedirs` with `isdir` to change write-based check to read-based check for static assets
**Testing**
**Checklist**
=> Replacing writing to site-packages with read check

docs/cli/export.mdx, preswald/utils.py, pyproject.toml
1. Add documentation for `preswald export` CLI command for exporting Preswald Apps as PDFs
2. Fixed playwright dependency (optional dep) in `pyproject.toml`
3. Ensured that in non-playwright installations, utils file does not break.
**Testing**
Tested within pyodide, using dist package. And tested on examples.
**Checklist**
=> Fix playwright dependency and add documentation for pdf export

preswald/templates/default/hello.py.template
* refactored `hello.py.template` to isolate Preswald display functions (`text`, `plotly`, `table`)
* moved all preswald UI calls (`text(...)`, `plotly(...)`, etc) to the bottom of the script
* switched `from preswald import ...` to just `import preswald` for clearer separation of concerns
* now all display logic goes through `preswald.<fn>` which is easier to spot, grep, and update
* avoids mixing preswald display logic with data/plot setup logic
* makes it easier to reuse or test logic without running UI display code mid-script
* fixes duplicate rendering (e.g. `text(...)` was called both directly and via `preswald.text(...)`)
* removes redundant `pd.read_csv(...)` call since `get_df('sample_csv')` already handles it via `connect()`
=> Clean up hello.py.template to separate display logic

preswald/utils.py
Remove html export directory from serialization to avoid recursively bundling in assets and exports.
**Testing**
All existing exports work as intended, without duplication
=> Remove html export directory from serialization

frontend/src/utils/websocket.js
---
title: 'fix(websocket): avoid stale cache when loading project_fs.json'
labels: 'bug'
assignees: ''
---
Fixes https://trello.com/c/SiqJtJnH/2709-bug-fix-websocket-js-is-fetching-projectfsjson-from-disk-cache
Previously, `project_fs.json` was being loaded from disk cache, causing user script changes to be ignored on reload when running in Pyodide. This change sets the fetch cache mode to `'no-cache'`, allowing the browser to revalidate the file with the server and avoid serving stale data.
This appears to resolve the issue. If stale cache problems persist, we can switch to a more aggressive setting like `'no-store'`.
**Testing**  
Tested …
=> fix(websocket): avoid stale cache when loading project_fs.json

frontend/src/backend/worker.js, preswald/engine/transformers/reactive_runtime.py
---
title: 'fix(pyodide): ensure matplotlib agg backend is set to enable figure rendering'
labels: 'bug'
assignees: ''
---
Fixes [Trello Card #2708](https://trello.com/c/4gPpK8ZX/2708-fix-matplotlib-implicit-rendering-issue-when-run-in-pyodide-show-does-not-render-anything)
Configures matplotlib backend in `worker.js` during Pyodide initialization.  
This approach ensures that all scripts use the `'agg'` backend by default in Pyodide, resolving figure rendering failures caused by the default `wasm_backend`.  
**Testing**  
- Confirmed that `fig.show()` now renders correctly in Pyodide without requiring explicit backend configuration in user …
=> fix(pyodide): ensure matplotlib agg backend is set to enable figure rendering

frontend/src/components/ErrorsReport.jsx, preswald/engine/base_service.py, preswald/engine/runner.py, preswald/engine/transformers/reactive_runtime.py, preswald/interfaces/render/error_registry.py, preswald/interfaces/workflow.py, preswald/utils.py
---
title: 'feat(errors): add runtime error reporting for reactive atoms'
labels: 'enhancement'
assignees: ''
---
Stacked on: https://github.com/StructuredLabs/preswald/pull/751  
Implements follow-up improvements to: feat(errors): implement error handling and reporting for AutoAtomTransformer (#751)
This PR introduces runtime error reporting for reactive atoms.
Previously, if a reactive atom raised an exception during execution, it would only appear in the browser console or logs — there was no structured mechanism for surfacing these errors to the user or frontend. This change addresses that gap by:
- Capturing uncaught exceptions raised during atom execution …
=> feat(errors): add runtime error reporting for reactive atoms

preswald/engine/render_tracking.py, preswald/utils.py
Previously, `with_render_tracking` would infer a `callsite_hint` using stack inspection when none was provided, which could result in incorrect IDs from stdlib or venv code. This fallback has been removed.
Instead, `generate_stable_id` reliably falls back to `get_user_code_callsite`, which filters out venvs and site-packages using absolute path prefixes.
This ensures that lifted components without explicit callsite_hint receive stable and user script IDs.
---
name: Pull Request  
about: Create a pull request to contribute to the project  
title: "fix(runtime): remove incorrect callsite_hint fallback from render tracking"  
labels: bug  
assignees: ''
---
Fixes https://trello.com/c/xC7FmqS9/2742-preswald-render-tracking-callsitehint-fallback-resolves-incorrect-callsite-t …
=> fix(runtime): remove incorrect callsite_hint fallback from render tracking"

preswald/engine/transformers/reactive_runtime.py
Previously, known component calls lifted via _lift_statements could omit the `component_id` keyword in the AST if routed through `_lift_consumer_stmt`. This led to inconsistent component identity and diffing issues.
This change ensures that all known component calls receive a stable `component_id` argument before being lifted, regardless of path taken.
---
name: Pull Request  
about: Create a pull request to contribute to the project  
title: 'fix(ast): inject missing component_id into known component calls'  
labels: 'bug'  
assignees: ''
Fixes https://trello.com/c/jmU7tAXj/2743-preswald-consumer-components-do-not-inject-componentid-after-being-lifted-causing-fallback-to-infer-the-correct-componentid
- Injects `component_id` into known …
=> fix(ast): inject missing component_id into known component calls

frontend/src/components/DynamicComponents.jsx
The `id` prop was not being passed to the ChatWidget and was accidentally misplaced in the `onChange` handler, causing an assignment to an undeclared identifier. This runtime error silently broke the chat widget and prevented the AI from responding to user prompts.
---
name: Pull Request  
about: Create a pull request to contribute to the project  
title: 'fix(chat): restore AI responses by passing correct id to ChatWidget'  
labels: 'bug'  
assignees: ''  
---
Fixes https://trello.com/c/PuXU7sVc/2744-preswald-chatwidget-onchange-error-breaks-communication-with-ai
- Replaced incorrect line `id = { componentId };` with `id={componentId}` in the ChatWidget instantiation  
- This ensures the `ChatWidget` receives the `id` prop, enabling proper …
=> fix(chat): restore AI responses by passing correct id to ChatWidget
